Repository danmooozi/kimbap.js, pull requests merged in 2023-10, with the labels that each got.

#9 Week3 irang
  main.js
  package.json
  src/index.js
  src/transform/constants/index.js
  src/transform/index.js
  src/transform/test/index.test.js
  src/transform/test/utils.js
  src/transform/test/utils/index.js
  src/transform/transform-esm-to-cjs.js
  src/transform/transform-strict-mode.js
  src/util/assertion.js
Labels: 🔨 refactor

#11 feat(parser): 각 모듈 간의 호환성이 보장되도록 코드 수정
  src/parser/index.js
Labels: 🔨 refactor

#12 refactor(output): utils 분리 및 리팩터링
  src/output/index.js
  src/output/output.js
  src/output/template.js
  src/util/file.js
  src/util/path.js
  src/util/string.js
Labels: 🔨 refactor

#13 Refactor: import/export 경로 수정 및 번들러 동작 확인
  src/cli/index.js
  src/index.js
  src/output/index.js
  src/output/template.js
  src/parser/index.js
Labels: 🔨 refactor

#14 feat: class 처리기능 추가
  src/transform/transform-esm-to-cjs.js
Labels: enhancement

#17 fix: node_modules 폴더를 찾을 수 없을 경우 Error throw
  src/parser/index.js
Labels: ✨ feature

#16 배포 커맨드
  .github/workflows/release.yml
  .npmignore
  README.md
  package.json
Labels: ✨ feature
